language: scala

scala:
  - 2.12.3

branches:
  only:
    - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION "project owe" coverage "testOnly owe.test.specs.*"
  - sbt ++$TRAVIS_SCALA_VERSION "project owe" coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - sbt coveralls
