addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.9")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.2.6")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.3.1")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
